apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-dev
type: Opaque
data:
  postgres-password: dXNlcm5hbWU=
  postgres-user: cGFzc3dvcmQ=
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
  namespace: todo-dev
data:
  database_url: postgres-service
  database_name: ToDo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: todo-dev
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: todo-server
          image: mahmudsharipov/todoserver:1.31
          resources:
            limits:
              memory: "3Gi"
              cpu: "1"
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: Database__User
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: Database__Server
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: database_url
            - name: Database__Name
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: todo-server-service
  namespace: todo-dev
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 1555
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-server-ingress
  namespace: todo-dev
spec:
  ingressClassName: nginx
  rules:
    - host: api.localdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-server-service
                port:
                  number: 1555