apiVersion: v1
kind: Namespace
metadata:
  name: todo-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: todo-dev
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-dev
type: Opaque
data:
  postgres-password: dXNlcm5hbWU=
  postgres-user: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
  namespace: todo-dev
data:
  database_url: postgres-service
  database_name: ToDo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap
  namespace: todo-dev
data:
  server_url: http://todo-server-service.todo-dev.svc
